site_name: Watson
theme:
  name: material
  logo: images/logo-avatar.png
  favicon: images/logo-avatar.ico
  palette:
    primary: '#006aa7'
    accent: '#e67e22'
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - include-markdown:
      encoding: utf-8

markdown_extensions:
  - pymdownx.snippets

repo_url: https://github.com/nomis51/watson
repo_name: Source code

extra_css:
  - assets/custom.css

nav:
  - Home: index.md
  - Get started: get-started.md
  - Commands: commands.md
  - FAQ: faq.md
