# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*'

permissions:
  contents: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src
    
    outputs:
      version: ${{ steps.get_version.outputs.version }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Get git tag version
        id: get_version
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0)
          VERSION=${LATEST_TAG#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
        working-directory: src/Watson
      - name: Update csproj version
        run: |
          sed -i "s|<Version>.*</Version>|<Version>${{ env.VERSION }}</Version>|g" Watson/Watson.csproj
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Cleanup
        run: rm -rf bin && rm -rf obj
        working-directory: src/Watson
      - name: Restore dependencies
        run: dotnet restore Watson/Watson.csproj
      - name: Publish
        run: dotnet publish Watson/Watson.csproj --configuration Release --output ./output --self-contained false --runtime linux-x64
      - name: Zip release
        run: cd ./output && zip -r Watson.${{ env.VERSION }}-linux-x64.zip .
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: watson-zip
          path: ./src/output/Watson.${{ env.VERSION }}-linux-x64.zip
  #      - name: Package
  #        run: dotnet pack --configuration Release
  #      - name: Publish
  #        run: dotnet nuget push Watson.$VERSION.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: watson-zip
          path: .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: Watson.${{ needs.build.outputs.version }}-linux-x64.zip