name: Build and publish application

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        runtime: [ 'win-x64', 'linux-x64' ]
        include:
          - runtime: win-x64
          - runtime: linux-x64

    defaults:
      run:
        working-directory: src
    
    outputs:
      version: ${{ steps.get_version.outputs.version }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Get version
        id: get_version
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0)
          VERSION=${LATEST_TAG#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
        working-directory: src/Watson
      - name: Update csproj version
        run: |
          sed -i "s|<Version>.*</Version>|<Version>${{ env.VERSION }}</Version>|g" Watson/Watson.csproj
          sed -i "s|<FileVersion>.*</FileVersion>|<FileVersion>${{ env.VERSION }}</FileVersion>|g" Watson/Watson.csproj
          sed -i "s|<PackageVersion>.*</PackageVersion>|<PackageVersion>${{ env.VERSION }}</PackageVersion>|g" Watson/Watson.csproj
      - name: Restore dependencies for tests
        run: dotnet restore
      - name: Build for tests
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal || exit 1
        working-directory: src/Watson
      - name: Restore dependencies for release
        run: dotnet restore Watson/Watson.csproj
      - name: Publish release
        run: dotnet publish Watson/Watson.csproj --configuration Release --output ./output --self-contained false --runtime ${{ matrix.runtime }}
      - name: Zip release
        run: cd ./output && zip -r Watson.${{ env.VERSION }}-${{ matrix.runtime }}.zip .
      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: Watson.${{ env.VERSION }}-${{ matrix.runtime }}.zip
          path: ./src/output/Watson.${{ env.VERSION }}-${{ matrix.runtime }}.zip
      - name: Build release for nuget
        run: dotnet build Watson/Watson.csproj --configuration Release --runtime ${{ matrix.runtime }}
      - name: Package release for nuget
        run: dotnet pack Watson/Watson.csproj --configuration Release --runtime ${{ matrix.runtime }} --output ./nupkg
      - name: Upload nuget artifact
        uses: actions/upload-artifact@v4
        with:
          name: Nomis51.Watson.${{ env.VERSION }}-${{ matrix.runtime }}.nupkg
          path: ./src/nupkg/Nomis51.Watson.${{ env.VERSION }}.nupkg

  github_release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
      - name: Download win-x64 artifact
        uses: actions/download-artifact@v4
        with:
          name: Watson.${{ needs.build.outputs.version }}-win-x64.zip
          path: .

      - name: Download linux-x64 artifact
        uses: actions/download-artifact@v4
        with:
          name: Watson.${{ needs.build.outputs.version }}-linux-x64.zip
          path: .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            Watson.${{ needs.build.outputs.version }}-win-x64.zip
            Watson.${{ needs.build.outputs.version }}-linux-x64.zip
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: |
            Release notes for ${{ github.ref_name }}

  nuget_publish:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
      - name: Download win-x64 artifact
        uses: actions/download-artifact@v4
        with:
          name: Nomis51.Watson.${{ needs.build.outputs.version }}-win-x64.nupkg
          path: artifact_dir

      - name: Rename nupkg
        run: |
          ls -R artifact_dir
          NUPKG_FILE=$(find artifact_dir -name "*.nupkg" | head -n 1)
          if [[ -z "$NUPKG_FILE" ]]; then
            echo "Error: No NuGet package found!"
            exit 1
          fi
          mv "$NUPKG_FILE" "Nomis51.Watson.${{ needs.build.outputs.version }}.nupkg"
        shell: bash

      - name: Publish Nuget
        run: dotnet nuget push Nomis51.Watson.${{ needs.build.outputs.version }}.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

  winget_publish:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout WinGet Tools
        uses: actions/checkout@v4

      - name: Download win-x64 Release Artifact
        uses: actions/download-artifact@v4
        with:
          name: Watson.${{ needs.build.outputs.version }}-win-x64.zip
          path: ./winget-package

      - name: Install WinGet Tools
        run: |
          sudo apt update
          sudo apt install -y p7zip-full
          wget https://github.com/microsoft/winget-cli/releases/latest/download/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
          7z x Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle -o./winget

      - name: Generate WinGet Manifest
        run: |
          mkdir -p ./winget-package/manifest
          cat <<EOF > ./winget-package/manifest/Nomis51.Watson.yaml
          PackageIdentifier: Nomis51.Watson
          PackageVersion: ${{ needs.build.outputs.version }}
          Publisher: Nomis51
          PackageName: Watson
          License: MIT
          InstallerType: zip
          Installers:
            - Architecture: x64
              InstallerUrl: https://github.com/${{ github.repository }}/releases/download/v${{ needs.build.outputs.version }}/Watson.${{ needs.build.outputs.version }}-win-x64.zip
              InstallerSha256: $(sha256sum ./winget-package/Watson.${{ needs.build.outputs.version }}-win-x64.zip | awk '{print $1}')
          ShortDescription: Your tool description here
          EOF

      - name: Submit Package to WinGet
        run: |
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
          gh repo clone https://github.com/microsoft/winget-pkgs.git
          
          mkdir -p winget-pkgs/manifests/n/Nomis51/Watson
          
          cp -r ./winget-package/manifest/* winget-pkgs/manifests/n/Nomis51/Watson
          
          cd winget-pkgs
          git checkout -b add-nomis51-watson-${{ needs.build.outputs.version }}

          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"

          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/microsoft/winget-pkgs.git

          git add .
          git commit -m "Add Watson ${{ needs.build.outputs.version }} to WinGet"
          git push origin add-nomis51-watson-${{ needs.build.outputs.version }}
          gh pr create --base master --head add-nomis51-watson-${{ needs.build.outputs.version }} --title "Add Watson ${{ needs.build.outputs.version }} to WinGet" --body "Automated submission of Watson ${{ needs.build.outputs.version }}"