# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Get version
        id: get_version
        run: echo "VERSION=$(grep -oP '(?<=<Version>)[^<]+' Watson.csproj)" >> $GITHUB_ENV
        working-directory: src/Watson
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Publish
        run: dotnet publish --no-build --configuration Release --output ./output
      - name: Zip release
        run: zip -r Watson.$VERSION.zip ./output  
      - name: Upload to GitHub Release
        uses: gh action upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./Watson.$VERSION.zip
          asset_name: Watson.$VERSION.zip
          asset_content_type: application/zip
#      - name: Package
#        run: dotnet pack --configuration Release
#      - name: Publish
#        run: dotnet nuget push Watson.$VERSION.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./Watson.$VERSION.zip